language: node_js

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run db:migrate

env:
  global:
    - SQL_USERNAME=postgres
    - SQL_TEST_DATABASE=travis_ci_test
